a=input("Enter the First Name")
print("My Name is",a)
a=input("Enter the Last Name")
print("My Last Name is",a)
a=input("Enter the Mobile Number")
print("Enter the Mobile Number",a)
a=input("Enter the email-id")
print("My email-id is",a)
a=input("Enter the Date of Birth")
print( "My Date of Birth",a)
a=input("Enter the Age:")
print("My Age is",a) 
a=input("Enter the Address")
print("My Address is",a)
a=input("Enter the Pincode")
print( "My Pincode :", a)
